---
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Prework"
subtitle: ""
summary: ""
authors: []
tags: []
categories: []
date: 
lastmod: 2020-09-11T11:17:19-07:00
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  # caption: <span>Photo by <a href="https://stock.adobe.com/contributor/205968087/surfupvector?load_type=author&prev_url=detail">Surfup Vector</a>
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

Hello! Welcome to the 5th Annual UO R Bootcamp. There are a few things we'd like you to do before we get started to make things run as smoothly as possible. 

:::clock
If possible, please try to complete this checklist *before* the first UO R Bootcamp session. Thank you!
:::


***

<br> 

1) Make sure you have a [Zoom account](https://service.uoregon.edu/TDClient/2030/Portal/KB/ArticleDet?ID=101392) set up through the University of Oregon. We will use the same Zoom link for each day of the bootcamp. You will receive the link through email and slack.

2) Join the [Slack workspace](https://uodatascience.slack.com/). This is how we will primarily be communicating with each other, and it is the best place to ask questions outside of the scheduled bootcamp hours. We'll be using the channel `#bootcamp2022`. You should have received an email invitation to join the `SlackRs` workspace. If you haven't received an invitation, send Cameron an email at [ckay@uoregon.edu](mailto:ckay@uoregon.edu). When you join, please introduce yourself and say hello in the `#bootcamp2022` channel!

3) Download and install both [R](https://cran.r-project.org) and [RStudio](https://www.rstudio.com/products/rstudio/download/). [R](https://cran.r-project.org) is free and, for the purposes of the bootcamp, you will only need the free version of [RStudio](https://cran.r-project.org). If you have any trouble downloading or opening [R](https://cran.r-project.org) or [RStudio](https://www.rstudio.com/products/rstudio/download/), please let one of the UO R Bootcamp team members know, and we will do our best to help you solve the issue.

4) Download the [materials and exercises](https://drive.google.com/drive/folders/1m3GpSyiV7ISHS_jvzK4M98sangzMmbqr?usp=sharing) (these will be added by 09/16/2022) for the UO R Bootcamp. We will be working through the materials and exercises together during the bootcamp.

5) Review the [Code of Conduct](/#code_of_conduct).

6) *Optional* - Download [Google Chrome](https://www.google.com/chrome/) if you don't have it already. The materials on this website are best viewed with Chrome. We've found that using other browsers (e.g., Firefox, Safari) can lead to some technical difficulties.

Looking forward to seeing you all soon. Hopefully we'll have you loving R in no time!

-Cameron


